### ISSUE TITLE
Implement VPBlind circuit

### ISSUE THREAD

**Issue by ghost** [anoma/taiga#1]
For first iteration, we want to use a separate circuit for VP privacy. In the long run, this may take a different approach with Accumulation.

This requires:
- [ ] Analyze the protocol to ensure the blinding polynomial is large enough degree
- [ ] Implement in-circuit Vesta elliptic curve arithmetic
- [ ] Implement in-circuit addition of blinding polynomial
- [ ] Implement `com_vp` opening and check against blinded VP in-circuit 
- [ ] Implement BLAKE2s gadget or other dual-curve commitment opening (privacy depends on heliaxdev/pbc-playground#8)
- [ ] Build the VPBlind circuit over the Pallas curve
- [ ] Implement non-native arithmetic and build VPBlind over Vesta curve
- [ ] Implement aggregating VPBlind proofs with proofs of other circuits
- [ ] Perform benchmarks of different approaches
- [ ] Document VPBlind in spec
- [ ] Implement tests

**Comment by simonmasson** [comment]
We now have an almost complete implementation of Taiga and circuits are quite large. One possible improvement for the blinding circuit is the implementation of GLV for the outer curve (BW6) so that scalar multiplication circuit is smaller.

**Comment by simonmasson** [comment]
If I understood correctly, the accumulation method for blinding would also require scalar multiplications over the outer curve, so it is probably worth investigating this improvement.

**Comment by cwgoes** [comment]
No longer relevant because we are using Halo2 recursion.
