### ISSUE TITLE
Improve the inner confusing `address` naming

### ISSUE THREAD

**Issue by XuyangSong** [anoma/taiga#123]
As described in #108 :
> The `user_address`(user_address = Com( Com(send_vp, nk), recv_vp)) will be removed. Instead, add an inner `address` variable(address = hash(vp_data_nonhashed, nk_com)). And the `address` will go to `NoteCommitment.` Does it make sense that we still use an address here? Otherwise, the `vp_data_nonhashed` and `nk_com` will go to `NoteCommitment` independently, and we need to extend the `SinsemillaCommit` since we add another 255 bits.

Rename the inner `address` or extend the `SinsemillaCommit.`

**Comment by vveiln** [comment]
I would say that extending the note commitment would make more sense if we don't need to use this variable somewhere else. I looked through the code quickly and it seems like there is no special use for that structure, but I might be wrong. 

If there is a special use (that doesn't apply to other fields of the note, e.g. some special check for `app_data_dynamic` and `nk_com`), renaming would work better, but it is hard to tell what should be the new name then

**Comment by XuyangSong** [comment]
Fix it after we have the key design. #132
