### ISSUE TITLE
Taiga: refactor transaction struct and verification process after integrating the function privacy

### ISSUE THREAD

**Issue by XuyangSong** [anoma/taiga#149]
customer: @mariari
performer: @XuyangSong 
deadline: null
estimated: null
started: null
actual: null
completed: null
confirmed: null
dependencies:
- [ ]

---

Based on #246 
VP proofs and public inputs are publicly verified in the transaction execution.
Replace VP proofs with verifier proofs in (partial) transactions once we have the recursive halo2.

**Comment by Acentelles** [comment]
To be re-evaluated after planning #246
