### ISSUE TITLE
Move to Short Weierstrass representation in Plonk implementation

### ISSUE THREAD

**Issue by simonmasson** [anoma/taiga#33]
For flexibility, we would like to have curve arithmetic circuits in Short Weierstrass coordinates. It would allow us using Pasta curves if we want to switch to IPA polynomial commitment. It needs to be done directly in `heliaxdev/ark-plonk` though.

**Comment by cwgoes** [comment]
@simonmasson Do you know the status of this? We're not using ZKGarage PLONK anymore.

**Comment by simonmasson** [comment]
In the long term, it would be good to have it in arkplonk, but in the context of Taiga I don't think we will use it. We can close it and create an issue in arkworks-rs repo instead, maybe.
