### ISSUE TITLE
Verifiable note encryption

### ISSUE THREAD

**Issue by joebebel** [anoma/taiga#7]
This issue is to add verifiable encryption to the output note encryption. This is necessary because VP-authorized shielded transactions are generated by third parties, and in the current design, that third party always has the option to discard the output note instead of distributing it. The only way to remove this option is to use verifiable encryption for certain fields of the output note.

This should be "opt-in" (as chosen by the VP) because it is not necessary for all transactions, and "opt-out" transactions should be able to avoid any and all potential side-effects from using verifiable encryption.

Practically, the address, value, and randomness commitment components of the note plaintext must be verifiably encrypted, and checked in the VP circuit. In the Orchard protocol, the diversifier is 88 bits, `v` is 64 bits, and `rseed` is 256 bits. Unfortunately this is larger than a 256-bit block, so some discussion of block cipher modes might be necessary.

1. We should implement and evaluate this verifiable encryption with both Poseidon and Blake2s. 
2. We should evaluate both the performance impact on the circuit size, and also the performance of blockchain scanning

**Comment by XuyangSong** [comment]
We will use the Poseidon permutation of width 3 in the DuplexSponge mode.
1. Key generation(DH key exchange)
  1.1  Get the receiver's public key $K = [k] G$
  1.2 Generate a random $r \in \mathbb{F}_q$
  1.3 Compute the shared encryption key $K_s = [r]K = (K_x, K_y) \in \mathbb{F}_p^2$
2. Encryption
The encryption message: $M \in \mathbb{F}_p^l$
The encryption nonce: $N < 2^{128}$
  2.1 Pad the message with zero to a multiple of RATE(2)
  2.2 Init the Poseidon state $S = (K_x, K_y, N + l * 2^{128})$
  2.3 Repeat for $0 \le i \lceil l  / 2 \rceil$
    a) Iterate Poseidon permutation(P) on state $S$: $S \leftarrow P(S)$
    b) Absorb two elements of the message: $S[0] = S[0] + M[2i]; S[1] = S[1] + M[2i + 1]$
    c) Output two elements of ciphertext: $C[2i] \leftarrow S[0]; C[2i+1] \leftarrow S[1]$
  2.4 Squeeze on S last time to get the MAC: $S \leftarrow P(S)$
  2.5 Add the MAC to the ciphertext: $C.add(S[0])$
3. Decryption
  Decryption nearly has the same process as encryption except for checking the MAC at the last step.

Reference:
[Poseidon Paper](https://eprint.iacr.org/2019/458.pdf)
[Duplexing the Sponge](https://eprint.iacr.org/2011/499.pdf)
[Encryption with Poseidon](https://dusk.network/uploads/Encryption-with-Poseidon.pdf)
[Design of Symmetric-Key Primitives for Advanced Cryptographic Protocols](https://eprint.iacr.org/2019/426.pdf)
